server:
  error:
    whitelabel:
      enabled: false
    path: '/error'
  servlet:
    encoding:
      charset: UTF-8
      force: true
  forward-headers-strategy: framework
  server-header: ''

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
  main:
    banner-mode: off
    log-startup-info: false
    cloud-platform: none
  jackson:
    serialization:
      CLOSE_CLOSEABLE: true
    default-property-inclusion: non_empty

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    config-url:
  api-docs:
    path: /api-docs